[tool.poetry]
name = "runner"
version = "0.1.0"
description = ""
authors = ["Cláudio Ventura <c.miguel.gomes.v@gmail.com>"]

[tool.poetry.dependencies]
python = "^2.7"
tweepy = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
